# Application Servers
[app]
192.168.56.104 
#192.168.56.95

# Database Servers
[db]
#192.168.56.96

# Group 'multi' will all servers
[multi:children]
app
db

# Variables that will be applied to all servers
[multi:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_python_intepreter=/usr/bin/python3
