# _*_ mode: ruby _*_
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION= "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Rocky"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant" , disabled: true
  config.vm.hostname = "nodejs.test"
  config.vm.network :private_network, ip: "192.168.56.104"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "c4playbook.yml"
  end
end
