# _*_ mode: ruby _*_
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION= "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # GEneral Vagrant VM Configuration
  config.vm.box = "hashicorp/bionic64"
  config.ssh.insert_key = false
#  config.ssh.username = "vagrant"
#  config.ssh.password = "vagrant"
#  config.ssh.private_key_path = "~/.ssh/"
  config.vm.synced_folder ".", "/vagrant" , disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "app7" do |app|
    app.vm.hostname = "orc-app7"
    app.vm.network :private_network, ip: "192.168.56.84"
  end

  # Application server 2
  config.vm.define "app6" do |app|
    app.vm.hostname = "orc-app8"
    app.vm.network :private_network, ip: "192.168.56.85"
  end

  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db4"
    db.vm.network :private_network, ip: "192.168.56.86"
  end
end
